# Generated by Django 4.2.6 on 2023-10-13 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CC', 'Conta Corrente'), ('CI', 'Conta Investimento'), ('CP', 'Conta Poupança')], default='', max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('saldo', models.FloatField(default=0.0)),
                ('incluir_saldo_no_dash_board', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
