# Generated by Django 4.2.6 on 2023-10-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='tipo',
            field=models.CharField(choices=[('CC', 'Conta Corrente'), ('CI', 'Conta Investimento'), ('CP', 'Conta Poupança')], default='', max_length=2),
        ),
    ]
