# Generated by Django 4.2.6 on 2023-10-16 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_remove_contabancaria_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='data_registro_conta',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
