# Generated by Django 4.2.6 on 2023-10-17 22:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_contabancaria_data_registro_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(choices=[('Visa', 'Visa'), ('Master', 'Master'), ('Elo', 'Elo'), ('Diners', 'Diners'), ('Amex', 'Amex'), ('Hypercard', 'Hypercard'), ('Outros', 'Outros')], default='', max_length=18)),
                ('descricao', models.TextField(max_length=200)),
                ('limite', models.FloatField(default=0.0)),
                ('incluir_saldo_no_dash_board', models.BooleanField(default=True)),
                ('dia_vencimento_fatura', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor deve ser maior ou igual a 1.'), django.core.validators.MaxValueValidator(31, message='O valor deve ser menor ou igual a 31.')])),
                ('dia_fechamento_fatura', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='O valor deve ser maior ou igual a 1.'), django.core.validators.MaxValueValidator(31, message='O valor deve ser menor ou igual a 31.')])),
                ('data_registro_cartao', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Conta Investimento', 'Conta Investimento'), ('Conta Poupança', 'Conta Poupança'), ('Carteira / Cash', 'Carteira / Cash')], default='', max_length=18)),
                ('descricao', models.TextField(max_length=200)),
                ('saldo', models.FloatField(default=0.0)),
                ('incluir_saldo_no_dashboard', models.BooleanField(default=True)),
                ('data_registro_conta', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ContaBancaria',
        ),
        migrations.AddField(
            model_name='cartaocredito',
            name='local_debito_fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.conta'),
        ),
    ]
