# Generated by Django 4.2.6 on 2023-10-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_conta_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='data_registro_conta',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='proprietario',
        ),
    ]
