# Generated by Django 4.2.6 on 2023-10-18 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_remove_conta_data_registro_conta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='data_registro_conta',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
