# Generated by Django 4.2.6 on 2023-10-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0009_cartaocredito_proprietario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaocredito',
            old_name='incluir_saldo_no_dash_board',
            new_name='incluir_saldo_no_dashboard',
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='bandeira',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Master', 'Master'), ('Elo', 'Elo'), ('Diners', 'Diners'), ('Amex', 'Amex'), ('Outros', 'Outros')], default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='dia_fechamento_fatura',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='dia_vencimento_fatura',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=1, max_length=2),
        ),
    ]
