# Generated by Django 4.2.6 on 2023-10-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0012_alter_cartaocredito_data_registro_cartao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
