# Generated by Django 4.2.6 on 2023-12-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracoes', '0013_alter_cartaocredito_limite_alter_conta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='local_debito_fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.conta'),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriadespesa',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriareceita',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conta',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('Conta Corrente', 'Conta Corrente'), ('Conta Investimento', 'Conta Investimento'), ('Conta Poupança', 'Conta Poupança'), ('Carteira / Cash', 'Carteira / Cash')], default='Conta Corrente', max_length=18),
        ),
        migrations.CreateModel(
            name='CorretoraInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('incluir_saldo_no_dashboard', models.BooleanField(default=True)),
                ('data_registro_conta', models.DateTimeField(default=django.utils.timezone.now)),
                ('proprietario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContaPrevidenciaPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PGBL', 'PGBL'), ('VGBL', 'VGBL')], default='PGBL', max_length=18)),
                ('descricao', models.TextField(max_length=200)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('incluir_saldo_no_dashboard', models.BooleanField(default=True)),
                ('data_registro_previdencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('corretora_de_investimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.corretorainvestimento')),
                ('proprietario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
