# Generated by Django 4.2.6 on 2023-12-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracoes', '0014_alter_cartaocredito_local_debito_fatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaocredito',
            name='local_debito_fatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.conta'),
        ),
        migrations.AlterField(
            model_name='cartaocredito',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriadespesa',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriareceita',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conta',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contaprevidenciaprivada',
            name='corretora_de_investimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.corretorainvestimento'),
        ),
        migrations.AlterField(
            model_name='contaprevidenciaprivada',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corretorainvestimento',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
