# Generated by Django 4.2.6 on 2024-01-06 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracoes', '0015_alter_cartaocredito_local_debito_fatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadespesa',
            name='proprietario',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
