# Generated by Django 4.2.6 on 2024-01-06 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuracoes', '0016_alter_categoriadespesa_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadespesa',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
