# Generated by Django 4.2.6 on 2024-02-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0017_alter_categoriadespesa_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaocredito',
            name='limite_disponivel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
