# Generated by Django 4.2.6 on 2023-10-20 19:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0013_alter_cartaocredito_limite_alter_conta_saldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descricao', models.TextField(max_length=200)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.categoriareceita')),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.conta')),
                ('proprietario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
