# Generated by Django 4.2.6 on 2023-10-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='credito_ja_realizado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3),
        ),
    ]
