# Generated by Django 4.2.6 on 2023-10-21 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_receita_credito_ja_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
