# Generated by Django 4.2.6 on 2023-12-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0015_alter_cartaocredito_local_debito_fatura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacoes', '0004_alter_receita_categoria_alter_receita_conta_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimentoprevidenciaprivada',
            name='conta_debito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.conta'),
        ),
        migrations.AlterField(
            model_name='investimentoprevidenciaprivada',
            name='conta_previdencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.contaprevidenciaprivada'),
        ),
        migrations.AlterField(
            model_name='investimentoprevidenciaprivada',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investimentorendafixa',
            name='conta_debito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.conta'),
        ),
        migrations.AlterField(
            model_name='investimentorendafixa',
            name='corretora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.corretorainvestimento'),
        ),
        migrations.AlterField(
            model_name='investimentorendafixa',
            name='investimento_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investimentorendavariavel',
            name='conta_debito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.conta'),
        ),
        migrations.AlterField(
            model_name='investimentorendavariavel',
            name='corretora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.corretorainvestimento'),
        ),
        migrations.AlterField(
            model_name='investimentorendavariavel',
            name='investimento_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investimentorendavariavel',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.categoriareceita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='conta_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.conta'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
