# Generated by Django 4.2.6 on 2023-12-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0005_alter_investimentoprevidenciaprivada_conta_debito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimentorendafixa',
            name='valor_resgate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investimentorendavariavel',
            name='valor_resgate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
