# Generated by Django 4.2.6 on 2023-12-26 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0006_investimentorendafixa_valor_resgate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimentorendafixa',
            name='data_resgate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
