# Generated by Django 4.2.6 on 2023-12-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0007_investimentorendafixa_data_resgate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimentorendafixa',
            old_name='irpf',
            new_name='irpf_aplicacao',
        ),
        migrations.RemoveField(
            model_name='investimentorendafixa',
            name='taxas_corretagem',
        ),
        migrations.RemoveField(
            model_name='investimentorendafixa',
            name='valor_resgate',
        ),
        migrations.AddField(
            model_name='investimentorendafixa',
            name='irpf_resgate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investimentorendafixa',
            name='taxas_corretagem_aplicacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investimentorendafixa',
            name='taxas_corretagem_resgate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investimentorendafixa',
            name='valor_resgate_liquido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
