# Generated by Django 4.2.6 on 2023-12-27 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0008_rename_irpf_investimentorendafixa_irpf_aplicacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investimentorendavariavel',
            old_name='irpf',
            new_name='irpf_aplicacao',
        ),
        migrations.RenameField(
            model_name='investimentorendavariavel',
            old_name='taxas_corretagem',
            new_name='taxas_corretagem_aplicacao',
        ),
        migrations.RenameField(
            model_name='investimentorendavariavel',
            old_name='valor_resgate',
            new_name='valor_resgate_liquido',
        ),
        migrations.AddField(
            model_name='investimentorendavariavel',
            name='data_resgate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investimentorendavariavel',
            name='irpf_resgate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investimentorendavariavel',
            name='taxas_corretagem_resgate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
