# Generated by Django 4.2.6 on 2023-12-29 19:34

import apps.configuracoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0009_rename_irpf_investimentorendavariavel_irpf_aplicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimentoprevidenciaprivada',
            name='investimento_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investimentoprevidenciaprivada',
            name='investimento_debitado_em_conta',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investimentorendafixa',
            name='investimento_debitado_em_conta',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investimentorendavariavel',
            name='investimento_debitado_em_conta',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investimentorendafixa',
            name='tipo_investimento_rf',
            field=models.CharField(choices=[('CDB', 'CDB'), ('CRI', 'CRI'), ('CRA', 'CRA'), ('DEBENTURE', 'DEBENTURE'), ('Fundo de RF', 'Fundo de RF'), ('LCA', 'LCA'), ('LCI', 'LCI'), ('POUPANÇA', 'POUPANÇA'), ('TESOURO', 'TESOURO'), ('Outros', 'Outros')], max_length=12),
        ),
        migrations.AlterField(
            model_name='investimentorendafixa',
            name='tipo_rentabilidade',
            field=models.CharField(choices=[('PÓS-FIXADA', 'PÓS-FIXADA'), ('PRÉ-FIXADA', 'PRÉ-FIXADA')], max_length=11),
        ),
        migrations.AlterField(
            model_name='investimentorendavariavel',
            name='tipo_investimento_rv',
            field=models.CharField(choices=[('Ações', 'Ações'), ('CRIPTO', 'CRIPTO'), ('FII', 'FII'), ('ETFs', 'ETFs'), ('Fundo de RV', 'Fundo de RV'), ('Outros', 'Outros')], max_length=12),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(max_length=200, verbose_name=apps.configuracoes.models.CategoriaReceita),
        ),
        migrations.AlterField(
            model_name='receita',
            name='conta_credito',
            field=models.CharField(max_length=200, verbose_name=apps.configuracoes.models.Conta),
        ),
        migrations.AlterField(
            model_name='receita',
            name='credito_ja_realizado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
