# Generated by Django 4.2.6 on 2023-12-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0015_alter_cartaocredito_local_debito_fatura_and_more'),
        ('operacoes', '0010_investimentoprevidenciaprivada_investimento_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.categoriareceita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='conta_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuracoes.conta'),
        ),
    ]
