# Generated by Django 4.2.6 on 2023-12-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0011_alter_receita_categoria_alter_receita_conta_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimentoprevidenciaprivada',
            name='investimento_ativo',
        ),
        migrations.RemoveField(
            model_name='investimentorendafixa',
            name='investimento_ativo',
        ),
        migrations.RemoveField(
            model_name='investimentorendavariavel',
            name='investimento_ativo',
        ),
        migrations.AddField(
            model_name='investimentoprevidenciaprivada',
            name='investimento_status',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('Ativo', 'Ativo'), ('Liquidado', 'Liquidado')], default='Ativo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investimentorendafixa',
            name='investimento_status',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('Ativo', 'Ativo'), ('Liquidado', 'Liquidado')], default='Ativo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investimentorendavariavel',
            name='investimento_status',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('Ativo', 'Ativo'), ('Liquidado', 'Liquidado')], default='Ativo', max_length=10),
            preserve_default=False,
        ),
    ]
