# Generated by Django 4.2.6 on 2023-12-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0012_remove_investimentoprevidenciaprivada_investimento_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investimentoprevidenciaprivada',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='investimentorendafixa',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='investimentorendafixa',
            name='taxa_negociada',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='investimentorendavariavel',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
