# Generated by Django 4.2.6 on 2024-01-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0017_alter_categoriadespesa_proprietario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacoes', '0014_receita_receita_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.categoriadespesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='conta_debito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.conta'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investimentoprevidenciaprivada',
            name='investimento_status',
            field=models.CharField(choices=[('Registrado', 'Registrado'), ('Efetivado', 'Efetivado')], max_length=10),
        ),
    ]
