# Generated by Django 4.2.6 on 2024-02-25 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0018_cartaocredito_limite_disponivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacoes', '0015_alter_despesa_categoria_alter_despesa_conta_debito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('numero_parcelas', models.IntegerField(default=1)),
                ('descricao', models.CharField(max_length=200)),
                ('despesa_status', models.CharField(choices=[('Registrada', 'Registrada'), ('Paga', 'Paga')], default='Registrada', max_length=10)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_primeira_fatura', models.DateTimeField(default=django.utils.timezone.now)),
                ('cartao_selecionado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.cartaocredito')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.categoriadespesa')),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
