# Generated by Django 4.2.6 on 2024-02-28 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0017_faturacartao_despesaindividualizadacartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesacartao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='despesacartao',
            name='data_primeira_fatura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='despesaindividualizadacartao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='despesaindividualizadacartao',
            name='qual_fatura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='faturacartao',
            name='data_fatura',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
