# Generated by Django 4.2.6 on 2024-03-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0018_cartaocredito_limite_disponivel'),
        ('operacoes', '0018_alter_despesacartao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesaindividualizadacartao',
            name='qual_cartao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.cartaocredito'),
        ),
        migrations.AlterField(
            model_name='faturacartao',
            name='fatura_status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Paga', 'Paga')], default='Aberta', max_length=10),
        ),
    ]
